# Generated by Django 6.1 on 2026-09-05 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс')),
                ('country', models.CharField(default='Россия', max_length=100, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион/Область')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Район')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=20, verbose_name='Дом')),
                ('building', models.CharField(blank=True, max_length=20, verbose_name='Корпус/Строение')),
                ('office', models.CharField(blank=True, max_length=20, verbose_name='Офис/Квартира')),
                ('entrance', models.CharField(blank=True, max_length=100, verbose_name='Вход/Подъезд')),
                ('floor', models.CharField(blank=True, max_length=20, verbose_name='Этаж')),
                ('landmark', models.CharField(blank=True, max_length=200, verbose_name='Ориентир')),
                ('full_address', models.CharField(blank=True, max_length=1000, verbose_name='Полный адрес')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'indexes': [models.Index(fields=['city', 'street'], name='events_addr_city_0282b6_idx'), models.Index(fields=['latitude', 'longitude'], name='events_addr_latitud_908492_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='events_cate_slug_1535d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=270, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='places/%Y/%m/', verbose_name='Главное фото')),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place', to='events.address', verbose_name='Адрес')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='URL')),
                ('description_short', models.CharField(max_length=500, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('moderation', 'На модерации'), ('published', 'Опубликовано'), ('cancelled', 'Отменено'), ('finished', 'Завершено')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('age_restriction', models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], default='16+', max_length=5, verbose_name='Возрастное ограничение')),
                ('schedule_type', models.CharField(choices=[('single', 'Разовое'), ('recurring', 'Повторяющееся'), ('period', 'Период')], default='single', max_length=20, verbose_name='Тип расписания')),
                ('start_date', models.DateField(db_index=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатное')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/', verbose_name='Главное изображение')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для связи')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон для связи')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('favorites_count', models.PositiveIntegerField(default=0, verbose_name='В избранном')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.category', verbose_name='Категория')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.place', verbose_name='Площадка')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['slug'], name='events_plac_slug_724747_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'start_date'], name='events_even_status_dfba18_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['place', 'start_date'], name='events_even_place_i_deabd0_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category', 'status'], name='events_even_categor_f85a11_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='events_even_slug_30eb0f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date'], name='events_even_start_d_d4b514_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_free'], name='events_even_is_free_20e3df_idx'),
        ),
    ]
