# Generated by Django 6.1 on 2026-09-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_status_dfba18_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_place_i_deabd0_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_categor_f85a11_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_slug_30eb0f_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_start_d_d4b514_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_is_free_20e3df_idx',
        ),
        migrations.RemoveField(
            model_name='address',
            name='full_address',
        ),
        migrations.AlterField(
            model_name='event',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('single', 'Однократное'), ('multiple', 'Многократное'), ('recurring', 'Повторяющееся')], max_length=20, null=True, verbose_name='Тип расписания'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='video_url',
        ),
    ]
