# Generated by Django 6.1 on 2026-09-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_events_even_status_dfba18_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('event', 'Событие'), ('place', 'Площадка'), ('category', 'Категория'), ('home', 'Главная'), ('search', 'Поиск')], db_index=True, max_length=20, verbose_name='Тип')),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID объекта')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Просмотров')),
            ],
            options={
                'verbose_name': 'Просмотр',
                'verbose_name_plural': 'Просмотры',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['kind', 'date'], name='events_page_kind_f2b315_idx'), models.Index(fields=['object_id', 'date'], name='events_page_object__88a174_idx')],
                'unique_together': {('kind', 'object_id', 'date')},
            },
        ),
    ]
