# Generated by Django 6.1 on 2026-09-13 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_emailotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('kultisk', 'kultisk.ru')], db_index=True, max_length=50, verbose_name='Источник')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успешно'), ('error', 'Ошибка')], db_index=True, default='running', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Запущен')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('events_created', models.PositiveIntegerField(default=0, verbose_name='Создано событий')),
                ('events_skipped', models.PositiveIntegerField(default=0, verbose_name='Пропущено (дубли)')),
                ('rows_parsed', models.PositiveIntegerField(default=0, verbose_name='Разобрано строк')),
                ('rows_skipped', models.PositiveIntegerField(default=0, verbose_name='Пропущено строк')),
                ('log_output', models.TextField(blank=True, verbose_name='Вывод')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to=settings.AUTH_USER_MODEL, verbose_name='Кто запустил')),
            ],
            options={
                'verbose_name': 'Импорт',
                'verbose_name_plural': 'Импорты',
                'ordering': ['-started_at'],
            },
        ),
    ]
