# Generated by Django 6.1 on 2026-09-13 15:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_importlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Просмотров')),
            ],
            options={
                'verbose_name': 'Просмотр категории',
                'verbose_name_plural': 'Просмотры категорий',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Просмотров')),
            ],
            options={
                'verbose_name': 'Просмотр события',
                'verbose_name_plural': 'Просмотры событий',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Просмотров')),
            ],
            options={
                'verbose_name': 'Просмотр площадки',
                'verbose_name_plural': 'Просмотры площадок',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Просмотров')),
                ('kind', models.CharField(choices=[('home', 'Главная'), ('search', 'Поиск')], db_index=True, max_length=20, verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Просмотр страницы',
                'verbose_name_plural': 'Просмотры страниц',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='address',
            name='events_addr_city_0282b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='address',
            name='events_addr_latitud_908492_idx',
        ),
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
        migrations.RemoveIndex(
            model_name='pageview',
            name='events_page_kind_f2b315_idx',
        ),
        migrations.RemoveIndex(
            model_name='pageview',
            name='events_page_object__88a174_idx',
        ),
        migrations.RemoveConstraint(
            model_name='pageview',
            name='unique_pageview_kind_object_date',
        ),
        migrations.DeleteModel(
            name='PageView',
        ),
        migrations.RemoveField(
            model_name='event',
            name='favorites_count',
        ),
        migrations.RemoveField(
            model_name='event',
            name='views_count',
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалено'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалено'),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалено'),
        ),
        migrations.AddField(
            model_name='importlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importlog',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалено'),
        ),
        migrations.AddField(
            model_name='importlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='place',
            name='building',
            field=models.CharField(blank=True, max_length=20, verbose_name='Корпус/Строение'),
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default='Искитим', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='place',
            name='entrance',
            field=models.CharField(blank=True, max_length=100, verbose_name='Вход/Подъезд'),
        ),
        migrations.AddField(
            model_name='place',
            name='floor',
            field=models.CharField(blank=True, max_length=20, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='place',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='place',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалено'),
        ),
        migrations.AddField(
            model_name='place',
            name='landmark',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ориентир'),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='place',
            name='office',
            field=models.CharField(blank=True, max_length=20, verbose_name='Офис/Квартира'),
        ),
        migrations.AddField(
            model_name='place',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс'),
        ),
        migrations.AddField(
            model_name='place',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_short',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='events_skipped',
            field=models.PositiveIntegerField(default=0, verbose_name='Пропущено событий'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='log_output',
            field=models.TextField(blank=True, verbose_name='Вывод команды'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='source',
            field=models.CharField(choices=[('kultisk', 'kultisk.ru'), ('manual', 'Вручную'), ('other', 'Другое')], db_index=True, default='kultisk', max_length=20, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Начат'),
        ),
        migrations.AddIndex(
            model_name='eventimage',
            index=models.Index(fields=['event', 'order'], name='events_even_event_i_530350_idx'),
        ),
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['source', 'status'], name='events_impo_source_76a860_idx'),
        ),
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['-started_at'], name='events_impo_started_9bf8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['city', 'street'], name='events_plac_city_67fa18_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['latitude', 'longitude'], name='events_plac_latitud_4e9ce6_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('title', 'start_date'), name='uniq_event_title_start_date'),
        ),
        migrations.AddField(
            model_name='categoryview',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='events.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='eventview',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='events.event', verbose_name='Событие'),
        ),
        migrations.AddField(
            model_name='placeview',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='events.place', verbose_name='Площадка'),
        ),
        migrations.AddConstraint(
            model_name='siteview',
            constraint=models.UniqueConstraint(fields=('kind', 'date'), name='uniq_siteview_kind_date'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddConstraint(
            model_name='categoryview',
            constraint=models.UniqueConstraint(fields=('category', 'date'), name='uniq_categoryview_category_date'),
        ),
        migrations.AddConstraint(
            model_name='eventview',
            constraint=models.UniqueConstraint(fields=('event', 'date'), name='uniq_eventview_event_date'),
        ),
        migrations.AddConstraint(
            model_name='placeview',
            constraint=models.UniqueConstraint(fields=('place', 'date'), name='uniq_placeview_place_date'),
        ),
    ]
