# Generated by Django 6.1 on 2026-09-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_categoryview_eventview_placeview_siteview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='vk_url',
            field=models.URLField(blank=True, help_text='Полная ссылка на страницу, например https://vk.com/club12345', verbose_name='ВКонтакте'),
        ),
    ]
