# Generated by Django 6.1 on 2026-09-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_place_vk_url'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='uniq_event_title_start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0, verbose_name='В избранном'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email организатора'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_name',
            field=models.CharField(blank=True, help_text='Название организации или имя. Необязательно.', max_length=255, verbose_name='Организатор'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон организатора'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_vk',
            field=models.URLField(blank=True, help_text='Полная ссылка, например https://vk.com/club12345', verbose_name='ВКонтакте организатора'),
        ),
        migrations.AddField(
            model_name='event',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_short',
            field=models.CharField(max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='contact_phone',
        ),
    ]
