# Generated by Django 6.1 on 2026-09-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_uniq_event_title_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coming_soon', models.BooleanField(default=False, help_text='Если включено — все не-админы видят заглушку coming_soon.', verbose_name='Режим «Скоро запуск»')),
                ('coming_soon_message', models.TextField(blank=True, help_text='Необязательно. Показывается на странице «Скоро запуск».', verbose_name='Сообщение на заглушке')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
