# Generated by Django 6.1 on 2026-09-14 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_sitesettings'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='categoryview',
            name='uniq_categoryview_category_date',
        ),
        migrations.RemoveConstraint(
            model_name='eventview',
            name='uniq_eventview_event_date',
        ),
        migrations.RemoveIndex(
            model_name='importlog',
            name='events_impo_source_76a860_idx',
        ),
        migrations.RemoveIndex(
            model_name='importlog',
            name='events_impo_started_9bf8fa_idx',
        ),
        migrations.RemoveConstraint(
            model_name='placeview',
            name='uniq_placeview_place_date',
        ),
        migrations.RemoveConstraint(
            model_name='siteview',
            name='uniq_siteview_kind_date',
        ),
        migrations.DeleteModel(
            name='SiteView',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='events_plac_latitud_4e9ce6_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='favorites_count',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='event',
            name='schedule_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='views_count',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.place', verbose_name='Площадка'),
        ),
        migrations.AlterField(
            model_name='place',
            name='vk_url',
            field=models.URLField(blank=True, help_text='Полная ссылка, например https://vk.com/club12345', verbose_name='ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='coming_soon',
            field=models.BooleanField(default=False, help_text='Если включено — все не-админы видят заглушку.', verbose_name='Режим «Скоро запуск»'),
        ),
        migrations.RemoveField(
            model_name='eventview',
            name='event',
        ),
        migrations.RemoveField(
            model_name='importlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='placeview',
            name='place',
        ),
        migrations.RemoveField(
            model_name='place',
            name='entrance',
        ),
        migrations.RemoveField(
            model_name='place',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='place',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='longitude',
        ),
        migrations.DeleteModel(
            name='CategoryView',
        ),
        migrations.DeleteModel(
            name='EventView',
        ),
        migrations.DeleteModel(
            name='ImportLog',
        ),
        migrations.DeleteModel(
            name='PlaceView',
        ),
    ]
