# Generated by Django 6.1 on 2026-09-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_categoryview_uniq_categoryview_category_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailotp',
            name='events_emai_user_id_42ed2d_idx',
        ),
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
