# Generated by Django 6.1 on 2026-09-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_remove_emailotp_events_emai_user_id_42ed2d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Например, slug события с kassir.ru', max_length=200, verbose_name='ID из внешнего источника'),
        ),
        migrations.AddField(
            model_name='event',
            name='external_url',
            field=models.URLField(blank=True, default='', help_text='Например, ссылка на kassir.ru', verbose_name='Ссылка на покупку билета'),
        ),
    ]
