# Generated by Django 6.1 on 2026-09-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_external_id_event_external_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='event',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='place',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('moderation', 'На модерации'), ('published', 'Опубликовано')], db_index=True, default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('moderation', 'На модерации'), ('published', 'Опубликовано')], db_index=True, default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('moderation', 'На модерации'), ('published', 'Опубликовано')], db_index=True, default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('moderation', 'На модерации'), ('published', 'Опубликовано')], db_index=True, default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
