# Generated by Django 6.1 on 2026-09-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_delete_sitesettings_remove_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='CSS-класс или эмодзи, например: 🎭', max_length=50, verbose_name='Иконка'),
        ),
    ]
