# Generated by Django 6.1 on 2026-09-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"seasons": [{"name": "Лето", "start": "05-16", "end": "08-31", "closed_days": [5, 6], "time": "10:00 — 17:00"}, ...]}. 0=понедельник, 6=воскресенье. Пусто = открыто каждый день.', verbose_name='Часы работы'),
        ),
    ]
