# Generated by Django 6.1 on 2026-09-16 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_place_working_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='working_hours',
        ),
        migrations.CreateModel(
            name='WorkingSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('moderation', 'На модерации'), ('published', 'Опубликовано')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('name', models.CharField(help_text='Например: «Летний период» или «Зимний период»', max_length=100, verbose_name='Название периода')),
                ('start_month', models.PositiveSmallIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], verbose_name='Месяц начала')),
                ('start_day', models.PositiveSmallIntegerField(help_text='Число от 1 до 31', verbose_name='День начала')),
                ('end_month', models.PositiveSmallIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], verbose_name='Месяц окончания')),
                ('end_day', models.PositiveSmallIntegerField(help_text='Число от 1 до 31', verbose_name='День окончания')),
                ('open_mon', models.BooleanField(default=True, verbose_name='Понедельник')),
                ('open_tue', models.BooleanField(default=True, verbose_name='Вторник')),
                ('open_wed', models.BooleanField(default=True, verbose_name='Среда')),
                ('open_thu', models.BooleanField(default=True, verbose_name='Четверг')),
                ('open_fri', models.BooleanField(default=True, verbose_name='Пятница')),
                ('open_sat', models.BooleanField(default=True, verbose_name='Суббота')),
                ('open_sun', models.BooleanField(default=True, verbose_name='Воскресенье')),
                ('time', models.CharField(blank=True, help_text='Например: «10:00 — 17:00, пт до 16:00»', max_length=200, verbose_name='Часы работы')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_seasons', to='events.place', verbose_name='Площадка')),
            ],
            options={
                'verbose_name': 'Сезон работы',
                'verbose_name_plural': 'Сезоны работы',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['place', 'order'], name='events_work_place_i_8396d8_idx')],
            },
        ),
    ]
