# Generated by Django 6.1 on 2026-09-18 15:16

import events.models.event
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_place_working_hours_workingseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Например: 54.6333', null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Например: 83.3000', null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.event.event_image_path, verbose_name='Главное изображение'),
        ),
    ]
