# Generated by Django 6.1 on 2026-09-14 20:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('city', models.CharField(default='Новосибирск', max_length=100, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('kassir_slug', models.CharField(blank=True, help_text='Например: novosibirskiy-gosudarstvennyy-akademicheskiy-tetar-operyi-i-baleta', max_length=255, null=True, unique=True, verbose_name='Slug на kassir.ru')),
            ],
            options={
                'verbose_name': 'Площадка гастролей',
                'verbose_name_plural': 'Площадки гастролей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TourEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID на kassir.ru')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(max_length=320, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('category', models.CharField(choices=[('theatre', 'Театр'), ('concert', 'Концерт'), ('show', 'Шоу'), ('other', 'Другое')], default='theatre', max_length=20, verbose_name='Категория')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Минимальная цена')),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальная цена')),
                ('price_text', models.CharField(blank=True, default='', help_text='Как на kassir.ru, например «от 3 000 ₽»', max_length=200, verbose_name='Цена (текстом)')),
                ('age_restriction', models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], default='16+', max_length=5, verbose_name='Возрастное ограничение')),
                ('image_url', models.URLField(blank=True, default='', verbose_name='URL изображения')),
                ('kassir_url', models.URLField(verbose_name='Ссылка на kassir.ru')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Снимается, если событие пропало с kassir.ru', verbose_name='Актуально')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('last_parsed_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний парсинг')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tours.tourvenue', verbose_name='Площадка')),
            ],
            options={
                'verbose_name': 'Гастрольное событие',
                'verbose_name_plural': 'Гастрольные события',
                'ordering': ['start_date', 'start_time'],
                'indexes': [models.Index(fields=['is_published', 'is_active', 'start_date'], name='tours_toure_is_publ_ed6e59_idx'), models.Index(fields=['category', 'start_date'], name='tours_toure_categor_eafc42_idx')],
            },
        ),
    ]
